name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0  
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mumble-web
        path: dist
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: dist/
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
